version: '3.4'

services:
    varnish:
        ports:
        - "${HTTP_HOST}:${HTTP_PORT}:80"

    frontend:
        user: ${DOCKER_USER}
        build:
            context: ./src
            dockerfile: dev.Dockerfile
        # command: bash -c "npm ci && npm run dev"
        command: bash -c "npm install && npm run dev"
        # command: bash -c "node ./server.js"
        ports:
            - "3001:3001" # HMR port
            - "3000:3000"
        volumes:
            - ./src:/app:cached
        environment:
            HOST: "0.0.0.0"
            TZ: ${TIMEZONE}
        tmpfs:
            - /tmp

